config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :users

  resources :gardens, only: [:show, :new, :create, :edit, :update]

  resources :garden_vegetables, only: [:create, :destroy]

  resources :tasks, only: [] do
    member do
      patch :mark_as_done
    end
  end
end

app/models/task.rb
class Task < ApplicationRecord
  STARTING_ACTIONS = ["seeding", "planting"]
  URGENCIES = ["not urgent", "urgent soon", "urgent", "very urgent"]
  belongs_to :garden_vegetable

  def mark_as_done!
    self.done = true
    self.date = DateTime.now
    self.save!

    set_following_tasks_due_dates if STARTING_ACTIONS.include? self.action
  end

  def followings_tasks
    self.garden_vegetable.tasks.where.not(id: self.id).where("step > ? ", self.step).order(step: :asc)
  end

  def final_urgency
    if step == 1
      first_tasks_urgency
    elsif step > 1 && date != nil
      urgency
    else
      "not urgent"
    end
  end

  def first_tasks_urgency
    # [1, nil, 3]
    if self.garden_vegetable.vegetable.planting_start == nil
      if DateTime.now < self.garden_vegetable.vegetable.seeding_start
        "not urgent"
      elsif DateTime.now >= self.garden_vegetable.vegetable.seeding_end - 14
        "very urgent"
      elsif DateTime.now <= self.garden_vegetable.vegetable.seeding_start + ((self.garden_vegetable.vegetable.harvesting_start - self.garden_vegetable.vegetable.seeding_start) / 2)
        "urgent"
      elsif DateTime.now >= self.garden_vegetable.vegetable.seeding_start
        "urgent soon"
      end
    # [1, 2, 3]
    elsif self.garden_vegetable.vegetable.seeding_start != nil && self.garden_vegetable.vegetable.planting_start != nil
      if DateTime.now < self.garden_vegetable.vegetable.seeding_start
        "not urgent"
      elsif DateTime.now >= self.garden_vegetable.vegetable.seeding_end - 7
        "very urgent"
      elsif DateTime.now <=self.garden_vegetable.vegetable.seeding_start + ((self.garden_vegetable.vegetable.planting_start - self.garden_vegetable.vegetable.seeding_start) / 2)
        "urgent"
      elsif DateTime.now >= self.garden_vegetable.vegetable.seeding_start
        "urgent soon"
      end
    # [nil, 2, 3]
    elsif self.garden_vegetable.vegetable.seeding_start == nil
      if DateTime.now < self.garden_vegetable.vegetable.planting_start
        "not urgent"
      elsif DateTime.now >= self.garden_vegetable.vegetable.planting_end - 7
        "very urgent"
      elsif DateTime.now <= self.garden_vegetable.vegetable.planting_start + ((self.garden_vegetable.vegetable.harvesting_start - self.garden_vegetable.vegetable.planting_start) / 2)
        "urgent"
      elsif DateTime.now >= self.garden_vegetable.vegetable.planting_start
        "urgent soon"
      end
    end
  end

  def urgency
    if self.date != nil
      if DateTime.now < self.date
        "not urgent"
      elsif DateTime.now >= self.date + 14
        "very urgent"
      elsif DateTime.now >= self.date + 7
        "urgent"
      elsif DateTime.now <= self.date + 7
        "urgent soon"
      end
    end
  end

  private

  def set_following_tasks_due_dates
    if self.action == "planting" && self.step == 1
      harvesting = followings_tasks.find_by(step: 2)
      harvesting.date = self.date + (self.garden_vegetable.vegetable.harvesting_start - self.garden_vegetable.vegetable.planting_start).days
      harvesting.save!
    elsif self.action == "seeding" && self.step == 1 && followings_tasks.find_by(step: 2).action == "harvesting"
      harvesting = followings_tasks.find_by(step: 2)
      harvesting.date = self.date + (self.garden_vegetable.vegetable.harvesting_start - self.garden_vegetable.vegetable.seeding_start).days
      harvesting.save!
    else
      planting = followings_tasks.find_by(step: 2)
      planting.date = self.date + (self.garden_vegetable.vegetable.planting_start - self.garden_vegetable.vegetable.seeding_start).days
      planting.save!

      harvesting = followings_tasks.find_by(step: 3)
      harvesting.date = self.date + (self.garden_vegetable.vegetable.harvesting_start - self.garden_vegetable.vegetable.seeding_start).days
      harvesting.save!
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def mark_as_done
    @task = Task.find(params[:id])
    @task.mark_as_done!
    redirect_to garden_path(@task.garden_vegetable.garden)
  end
end

app/views/tasks/_index.html.erb
<div class="tasks-vegetables">
  <% @tasks_not_done.each do |task| %>
    <% if task.step > 1 && task.date != nil || task.step == 1 && task.date == nil %>
      <div class="action-task d-flex justify-content-space-around">
        <div class="">
          <div class="action-color d-flex align-items-center justify-content-center">
            <% if task.step == 1 %>
              <% case task.first_tasks_urgency %>
                <% when "not urgent" %>
                  <%= image_tag "background-urgency/urgence_1.png", style: 'height:45px;opacity:0.5' %>
                <% when "very urgent" %>
                  <%= image_tag "background-urgency/urgence_4.png", style: 'height:45px;opacity:0.7' %>
                <% when "urgent" %>
                  <%= image_tag "background-urgency/urgence_3.png", style: 'height:45px;opacity:0.7' %>
                <% when "urgent soon" %>
                  <%= image_tag "background-urgency/urgence_2.png", style: 'height:45px;opacity:0.7' %>
              <% end %>
            <% elsif task.step > 1 && task.date != nil %>
              <% if task.step %>
                <% case task.urgency %>
                  <% when "not urgent" %>
                    <%= image_tag "background-urgency/urgence_1.png", style: 'height:45px;opacity:0.5' %>
                  <% when "very urgent" %>
                    <%= image_tag "background-urgency/urgence_4.png", style: 'height:45px;opacity:0.7' %>
                  <% when "urgent" %>
                    <%= image_tag "background-urgency/urgence_3.png", style: 'height:45px;opacity:0.7' %>
                  <% when "urgent soon" %>
                    <%= image_tag "background-urgency/urgence_2.png", style: 'height:45px;opacity:0.7' %>
                <% end %>
              <% end %>
            <% end %>

            <div class="action-logo">
              <% if task.step > 1 && task.date != nil || task.step == 1 && task.date == nil %>
                <% if task.action == "seeding" %>
                  <%= image_tag "icon-seeding-black.png" %>
                <% elsif task.action == "planting" %>
                  <%= image_tag "icon-planting-black.png" %>
                <% else %>
                  <%= image_tag "icon-harvesting-black.png" %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
        <div class="Action-title d-flex justify-content-evenly">
          <div class="specie-type d-flex align-items-center">
            <% if task.step > 1 && task.date != nil || task.step == 1 && task.date == nil %>
              <h6><%= task.action %> </h6>
              <h5> <%= task.garden_vegetable.vegetable.specie %></h5>
            <% end %>
          </div>
        </div>

        <div class="see-more d-flex align-items-center">
          <% if task.step > 1 && task.date != nil || task.step == 1 && task.date == nil %>
            <i class="far fa-question-circle button-plus" task_id="<%=task.id%>"></i>
          <% end %>
        </div>

      </div>
    <% end %>
  <% end %>
</div>

app/views/tasks/_show.html.erb
<%  @tasks_not_done.each do |task|%>
<div class="description-show display-none" data-task-id="<%= task.id %>">
  <div class="title-description">
    <h2><%= task.garden_vegetable.vegetable.specie.capitalize %> </h2>
  </div>
  <div class="d-flex">
    <p class="general-description">
      <%= task.garden_vegetable.vegetable.description %>      </p>
      <div class="vege-photo-description">
        <%= image_tag task.garden_vegetable.vegetable.photo_vegetable, class: "photo-description" %>
      </div>
    </div>
    <div class="title-description">
      <h3><%= task.action.capitalize %> </h3>
    </div>

    <div class="onglet-description">
      <div class="task-description">
        <% if task.action == "seeding" %>
        <% if task.garden_vegetable.vegetable.seeding_start?%>
        <div class="" id="nav-home-<%=task.garden_vegetable.vegetable.id%>">
          <div class="d-flex justify-content-between align-items-center">
            <h5><i class="fas fa-calendar-alt"></i> <span class="date-info">From </span>  <%= task.garden_vegetable.vegetable.seeding_start.strftime("%B")%>  <span class="date-info"> to </span> <%=task.garden_vegetable.vegetable.seeding_end.strftime("%B") %></span></h5>
            <%= link_to "Mark as done", mark_as_done_task_path(task.id), method: :patch, class: "button-done" %>
          </div>
          <p>
            <%= task.garden_vegetable.vegetable.sedding_desription%>
          </p>
          </div>
          <% end %>
          <% elsif task.action == "planting" %>
          <% if task.garden_vegetable.vegetable.planting_start?%>
          <div class="" id="nav-profile-<%=task.garden_vegetable.vegetable.id%>">
            <div class="d-flex justify-content-between align-items-center">
              <h5><i class="fas fa-calendar-alt"></i> <span class="date-info">From </span>  <%= task.garden_vegetable.vegetable.planting_start.strftime("%B")%>  <span class="date-info"> to </span> <%= task.garden_vegetable.vegetable.planting_end.strftime("%B") %></span></h5>
              <%= link_to "Mark as done", mark_as_done_task_path(task.id), method: :patch, class: "button-done" %>
            </div>
            <p>
              <%= task.garden_vegetable.vegetable.planting_description%>
            </p>
            </div>
            <% end %>
            <% elsif task.action == "harvesting" %>
            <div class="" id="nav-contact-<%=task.garden_vegetable.vegetable.id%>">
              <div class="d-flex justify-content-between align-items-center">
                <h5><i class="fas fa-calendar-alt"></i> <span class="date-info">From </span> <%= task.garden_vegetable.vegetable.harvesting_start.strftime("%B")%>  <span class="date-info"> to </span> <%= task.garden_vegetable.vegetable.harvesting_end.strftime("%B") %></span></h5>
                <%= link_to "Mark as done", mark_as_done_task_path(task.id), method: :patch, class: "button-done"%>
              </div>
              <p>
                <%= task.garden_vegetable.vegetable.harvesting_description%>
              </p>
            </div>
            <% end %>
          </div>
        </div>
      </div>
      <% end %>