config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :users

  resources :gardens, only: [:show, :new, :create, :edit, :update]

  resources :garden_vegetables, only: [:create, :destroy]

  resources :tasks, only: [] do
    member do
      patch :mark_as_done
    end
  end
end

app/views/pages/home.html.erb
<div class="home-page">
  <div class="home-bar">
    <div class="logo">
      <%= image_tag "Logo-Easy-Garden.png", style: "width:170px" %>
    </div>
    <%= link_to "My garden", garden_path(Garden.all.first.id), class: "btn-my-garden" %>
  </div>

  <div class="slogan">
    <h1>Draw it & Grow it</h1>
  </div>

  <div class="step-container align-items-center">

    <div class="step-content">
      <div class="step-number">
        <div class="step">
          <h2>Step 1</h2>
        </div>
      </div>
      <div class="step-infos">
        <div class="step-instruction">
          <h6>Pick the vegetables you want to grow</h6>
        </div>
        <div class="step-show step1">
          <%= image_tag "radish.png", style: "width:150px" %>
          <%= image_tag "zucchini.png", style: "width:150px" %>
          <%= image_tag "beans.png", style: "width:150px" %>
          <%= image_tag "tomato.png", style: "width:150px" %>
        </div>
      </div>
    </div>

    <div class="step-content">
      <div class="step-number">
        <div class="step">
          <h2>Step 2</h2>
        </div>
      </div>
      <div class="step-infos">
        <div class="step-instruction">
          <h6>Drag your choice into your garden </h6>
        </div>
        <div class="step-show step2">
          <%= image_tag "drag-example.png", style: "width:300px", class: "drag-exp" %>
          <%= image_tag "SchemaGarden.png", style: "width:450px" %>
        </div>
      </div>
    </div>

    <div class="step-content">
      <div class="step-number">
        <div class="step">
          <h2>Step 3</h2>
        </div>
      </div>
      <div class="step-infos">
        <div class="step-instruction">
          <h6>Now, just follow our lead</h6>
        </div>
        <div class="step-show step3">
          <div class="step3-task">
            <div class="d-flex justify-content-around">
            <%= image_tag "Seeding-task.png", style: "width:auto;height:50px;margin: 20px" %>
            <%= image_tag "Planting-task.png", style: "width:auto;height:50px;margin: 20px" %>
            </div>
            <%= image_tag "Harvesting-task.png", style: "width:auto;height:50px;margin: 20px" %>
          </div>
        </div>
      </div>
    </div>
    <div class="btn-create-garden ">
      <% if user_signed_in? %>
        <%= link_to "Go to my garden", garden_path(Garden.all.first.id)  %>
      <% else %>
        <%= link_to "Create my garden", new_user_registration_path  %>
      <% end %>
    </div>
  </div>
</div>