config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :users

  resources :gardens, only: [:show, :new, :create, :edit, :update]

  resources :garden_vegetables, only: [:create, :destroy]

  resources :tasks, only: [] do
    member do
      patch :mark_as_done
    end
  end
end

app/models/garden.rb
class Garden < ApplicationRecord
  belongs_to :user
  has_many :garden_vegetables, dependent: :destroy
  has_many :vegetables, through: :garden_vegetables
  has_many :tasks,      through: :garden_vegetables
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  before_action :load_garden, only: [:show, :edit]
  before_action :load_tasks, only: [:show, :edit]

  def show
    @garden_vegetables = GardenVegetable.all
    @vegetables = Vegetable.all
  end

  def edit
    @garden_vegetables = GardenVegetable.all
    @garden_vegetable = GardenVegetable.new
    @vegetables = Vegetable.all
  end

  def update
  end

  def new

  end

  def create

  end

  private

  def load_garden
    @garden = Garden.find(params[:id])
  end

  def load_tasks
    @tasks_not_done = @garden.tasks.where(done: false).order("step, date IS NOT NULL, date ASC")
    @tasks_not_done = @tasks_not_done.sort_by { |task| -Task::URGENCIES.index(task.final_urgency) }
    @tasks_per_veggie = @tasks_not_done.group_by(&:garden_vegetable)
  end
end

app/views/gardens/edit.html.erb
<div class="edit-container d-flex">
  <div class="sidebar-container">
    <%= link_to(image_tag("Logo-Easy-Garden.png", :title => "Home", class: "logo-easy-garden"), "/") %>
    <%#= link_to image_tag("Logo-Easy-Garden.png", class: "logo-easy-garden") %>
    <div class="title-sidebar">
      <h2>Vegetables</h2>
    </div>
    <%= render 'vegetables/index'%>
  </div>

  <div class="right-part">
    <div class="top-title d-flex justify-content-around">
      <div class="title-garden">
        <h1>Let's design my garden</h1>
        <h4>  Add vegetables in your virtual garden</h4>
      </div>
      <div class="garden-button">
        <form  action="/garden_vegetables" method="post" >
          <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
          <%= hidden_field_tag :garden_id, @garden.id %>
          <label class="hidden" for="data-spot"></label>
          <input class="hidden" type="text" id="data-spot" name="data-spot"></input>
          <button class="button-edit-save test-data">Save !</button>
        </form>
      </div>
    </div>

    <div>
      <%= render "shared/garden_draggable", garden_vegetables: @garden_vegetables, mode: "edit" %>    </div>


  </div>

  <div class="container-info">
    <div class="vegetable-description">
      <%= render 'vegetables/show' %>
    </div>
  </div>
</div>

app/views/gardens/new.html.erb
<div class="container-div">
  <div class="title-garden">
    <h1>Draw your garden</h1>
  </div>
  <%= render 'shared/sidebar' %>
</div>

app/views/gardens/show.html.erb
<% content_for :meta_title, "#{@garden_vegetables.name} is on #{DEFAULT_META["meta_product_name"]}" %>

<%# content_for :meta_description, @offer.description %>
<%# content_for :meta_image, cl_image_path(@garden_vegetables.photo.path) %>
<div class="container-div d-flex">

  <div class="sidebar-container">
    <%= link_to(image_tag("Logo-Easy-Garden.png", :title => "Home", class: "logo-easy-garden"), "/") %>
    <%#= image_tag("Logo-Easy-Garden.png", class: "logo-easy-garden") %>
    <div class="title-sidebar">
      <h2>Next tasks</h2>
    </div>
    <%= render 'tasks/index' %>
  </div>

  <div class="right-part">

    <div class="top-title d-flex justify-content-around">
      <div class="title-garden" >
        <h1>Take a look on your garden</h1>
        <h4>  Stay informed of the next steps</h4>

      </div>
      <div class="garden-button">
        <button class="button-edit-save"><%= link_to "Edit", edit_garden_path  %> </button>
      </div>
    </div>
    <div>
      <%= render "shared/garden_draggable", garden_vegetables: @garden_vegetables, mode: "show" %>
          </div>

  </div>



  <div class="container-info">
    <div class="vegetable-description">
      <%= render 'tasks/show' %>
    </div>
  </div>
</div>